### ISSUE TITLE
Input to the rand function?

### ISSUE THREAD

**Issue by Shreyas-NR** [gau-nernst/macaque-detection#2]
https://github.com/gau-nernst/macaque-detection/blob/d8eeaeffa6377fe5a43d5c6d8dfdad8491496a41/kv260_resnet18/resnet18.py#L22

Could you please explain what is 1, 3 in this line? `sample_inputs = torch.randn((1,3,224,224))`

**Comment by gau-nernst** [comment]
It is the shape (B, C, H, W) of the sample input. B is the batch size, C is the number of channels (3), H and W are the height and weight.

**Comment by Shreyas-NR** [comment]
@gau-nernst Thanks for the quick response.

Can you stress more on this? _"C is the number of channels (3)"_

**Comment by gau-nernst** [comment]
RGB images have 3 channels

**Comment by Shreyas-NR** [comment]
Great! Thank you so much for the help.
